export const WarehouseImportStatus = {
  WAITING: 'WAITING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  QUANTITY_CHECK : 'QUANTITY_CHECK',
  QUANTITY_VERIFIED : 'QUANTITY_VERIFIED',
  EXPORTED : 'EXPORTED'
};

export const WarehouseImportType = {
  NEW: 'NEW',
  RETURN: 'RETURN',
  EXPORT: 'EXPORT',
  EXPORT_TO_PROVIDER: 'EXPORT_TO_PROVIDER',
};
