export enum OrderStatus {
  WAITING = 'WAITING',
  APPROVED = 'APPROVED',
  CANCEL = 'CANCEL',
  CREATED = "CREATED",
  DELETED = 'DELETED',
  CREATE_COD = 'CREATE_COD',
  COD_APPROVED = 'COD_APPROVED',
  REJECTED = 'REJECTED',
  SUPPLY_WAITING = 'SUPPLY_WAITING',
  SHIPPING = 'SHIPPING',
  SUCCESS = 'SUCCESS',
  COD_CANCEL = 'COD_CANCEL'
}
