export enum StoreImportStatus {
    WAITING = 'WAITING',
    APPROVED = 'APPROVED',
    QUANTITY_CHECK = 'QUANTITY_CHECK',
    QUANTITY_VERIFIED = 'QUANTITY_VERIFIED',
    REJECTED = 'REJECTED',
    EXPORTED = 'EXPORTED',
}
