export const OrderStatus = {
  WAITING: 'WAITING',
  APPROVED: 'APPROVED',
  CREATE_COD: 'CREATE_COD',
  CANCEL: 'CANCEL',
  DELETED: 'DELETED',
  COD_APPROVED: 'COD_APPROVED',
  REJECTED: 'REJECTED',
  SUPPLY_WAITING: 'SUPPLY_WAITING',
  SHIPPING: 'SHIPPING',
  SUCCESS: 'SUCCESS',
  COD_CANCEL: 'COD_CANCEL'
};
