export const BillStatus = {
  CREATED: 'CREATED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SUPPLY_WAITING: 'SUPPLY_WAITING',
  SHIPPING: 'SHIPPING',
  SUCCESS: 'SUCCESS',
  CANCEL: 'CANCEL',
};
